### ISSUE TITLE
[Question] - What is the best way to clear data after a new deploy

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#911] opened 2021-07-27 16:41 UTC
Just checking if there is an easier approach than manually removing data.
Quite often (in dev) it's needed to remove old events after a new deploy because old events do not have required fields which are added in the new version. 
On local this is easy due to the simple file storage, but for DynamoDB this is a bit annoying.

**Comment by LaiaPerez88** [comment] 2021-07-27 16:42
Currently, this has to be done manually. You can use tools like [dynobase](https://dynobase.dev/) so it’s easier to clean up. However, we have created a nice-to-have issue to handle this: https://github.com/boostercloud/booster/issues/901 .

**Comment by thomas-advantitge** [comment] 2021-07-28 12:55
Meanwhile we've gone through all Booster core code and also saw some nice support for migrations, wasn't expecting that already! I see there is also already a ticket for the documentation of that https://github.com/boostercloud/booster/issues/327.

**Comment by jesusAlvSoto** [comment] 2022-05-24 09:24
Closing this ticket as the issue is addressed in #901

**Closed by jesusAlvSoto** 2022-05-24 09:24 UTC
Labels: question
