### ISSUE TITLE
Invalid token in aws/credentials file report: "Unable to determine default account and/or region"

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#68] opened 2020-04-29 17:52 UTC
**Environment**
➜  booster_projects nvm use node 
Now using node v13.3.0 (npm v6.13.1)
➜  booster_projects npm install -u -g @theagilemonkeys/booster-cli
/Users/gonzalogarcia/.nvm/versions/node/v13.3.0/bin/boost -> /Users/gonzalogarcia/.nvm/versions/node/v13.3.0/lib/node_modules/@theagilemonkeys/booster-cli/bin/run
+ @theagilemonkeys/booster-cli@0.0.43
updated 10 packages in 31.947s
➜  booster_projects boost -v                                      
@theagilemonkeys/booster-cli/0.0.43 darwin-x64 node-v13.3.0

**Steps to reproduce it:**

1. Create a new project
2. Update the credentials file with an invalid token

**Expected result**

A meaningful message like this one:
`➜  testing serverless deploy
Serverless: Packaging service...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The security token included in the request is invalid.`

**Result**

Booster error message about the `default account` is fine but Serverless message points me to the token issue which is the main issue:

`➜  issues boost deploy
ℹ boost deploy 🚀
✖ Unable to determine default account and/or region`

**Comment by glammers1** [comment] 2020-05-21 20:42
Hi, @NickSeagull that message was changed in this [PR](https://github.com/boostercloud/booster/commit/411dd8fc36555c39c186e008215fdb4b22dc8cde#diff-2e8a95c0e08b0d7fe94ab8481934adac), so now we get errors like this:

I am using CLI version 0.3.3.

- If there is no `credentials` file:

```
$ boost deploy -e production
ℹ boost deploy [production] 🚀
✖ Error: Unable to load default AWS account. Check that you have properly set your AWS credentials in `~/.aws/credentials` file or the corresponding environment variables. Refer to AWS documentation for more details https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html
    at getEnvironment (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:16:15)
    at bootstrap (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:32:17)
    at deployApp (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:53:30)
```

- If an invalid `access key` is provided:

```
$ boost deploy -e production
ℹ boost deploy [production] 🚀
✖ Error: Unable to load default AWS account. Check that you have properly set your AWS credentials in `~/.aws/credentials` file or the corresponding environment variables. Refer to AWS documentation for more details https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html
    at getEnvironment (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:16:15)
    at bootstrap (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:32:17)
    at deployApp (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:53:30)
```

- If an invalid `secret key` is provided:

```
$ boost deploy -e production
ℹ boost deploy [production] 🚀
ℹ Bootstraping the following environment: {"name":"Default environment","account":"155431809731","region":"us-east-1"}
✖ SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at Request.extractError (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

______________________

Just a heads up, in the context of this issue I've tried older versions of the CLI and with version 0.2.1 for example, the stack trace was not printed:

```
$ boost deploy -e production
ℹ boost deploy [production] 🚀
ℹ Bootstraping the following environment: {"name":"Default environment","account":"155431809731","region":"us-east-1"}
✖ The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

**Was that change intended?**

**Comment by NickSeagull** [comment] 2020-05-25 09:54
If on 0.3.3 everything works correctly we should not take care of older versions

**Comment by glammers1** [comment] 2020-05-25 10:45
Ok, in that case, I think the error messages are clear enough right now so you can close this issue. 

Apart from that, can you confirm if printing the stack trace is the expected behavior?

**Comment by NickSeagull** [comment] 2020-05-25 12:00
I think that it doesn't help much the user to see the stack trace, we can remove it

**Comment by glammers1** [comment] 2020-05-25 12:34
> I think that it doesn't help much the user to see the stack trace, we can remove it

Ok, I just opened #94. You can close this one. Thanks.

**Closed** 2020-05-25 16:58 UTC
Labels: bug, size: M
