### ISSUE TITLE
Documentation search page is not working

### ISSUE THREAD

**Issue by Fecony** [boostercloud/booster#1293] opened 2023-01-06 15:33 UTC
## Description
Documentation search is not working on search page
- try typing something in search bar
- scroll down and click "See all * results"

**Comment by javiertoledo** [comment] 2023-01-09 18:24
Good catch! I'll add a couple of screenshoots for extra clarity on how to reproduce:

Even when the search bar shows valid results, if you click in the "See all ## results" at the bottom of the popup:
![Screenshot 2023-01-09 at 18 22 14](https://user-images.githubusercontent.com/175096/211379876-179b277e-cf70-4eb2-a9f3-8cfe9995947c.png)

The page is shown empty:
![Screenshot 2023-01-09 at 18 23 55](https://user-images.githubusercontent.com/175096/211380144-3a0ff171-c3b6-4f45-af43-fc9b431fba06.png)

**Comment by javiertoledo** [comment] 2023-01-10 13:00
_From a conversation with @BorjaZarco:_ 

This seems to be a known issue with Algolia (https://github.com/facebook/docusaurus/issues/6693). We'll dig into it soon

**Comment by BorjaZarco** [comment] 2023-01-11 11:05
This has been fixed by following [this comment exactly](https://github.com/facebook/docusaurus/issues/6693#issuecomment-1162664549). We needed to change a config param on docusaurus, which was done in [this PR](https://github.com/boostercloud/booster/pull/1298)

Thank you for noting that @Fecony!

**Closed by BorjaZarco** 2023-01-11 11:05 UTC
Labels: bug 🐞, documentation, good first issue, dev-experience, difficulty: low, priority: medium
