### ISSUE TITLE
Booster.entity does not return the entity

### ISSUE THREAD

**Issue by AdrianLorenzoDev** [boostercloud/booster#918] opened 2021-07-30 12:40 UTC
# Bug Report

## Current Behavior

When the application runs the `Booster.entity()` asynchronous function, instead of returning the expected entity, it returns and object which contains the entity in the `value` attribute:

```json
{
    "entityTypeName_entityID_kind": "User-EXAMPLE_ID-snapshot",
    "version": 1,
    "value": {
        "id": "EXAMPLE_ID",
    },
    "snapshottedEventCreatedAt": "2021-07-30T12:20:07.459Z",
    "kind": "snapshot",
    "entityTypeName": "User",
    "entityTypeName_kind": "User-snapshot",
    "typeName": "User",
    "entityID": "EXAMPLE_ID",
    "createdAt": "2021-07-30T12:20:09.200Z",
    "requestID": "REQUEST_ID"
}
```

## Expected behavior

`Booster.entity()` should return the entity.

## Possible Solution

Using the `value` attribute from the object that is returned by this function. 

### Environment

- Booster version: 0.20.2
- Node/npm version: v16.5.0
- OS: macOS Big Sur 11.4

**Comment by AdrianLorenzoDev** [comment] 2021-07-30 12:49
It seems like it is related to [this line of code](https://github.com/boostercloud/booster/blob/main/packages/framework-core/src/booster.ts#L128), which calls [the following function](https://github.com/boostercloud/booster/blob/42fba9767bc386758f51324bdf3c2ba0984eda91/packages/framework-common-helpers/src/instances.ts#L3):

```typescript
export function createInstance<T>(instanceClass: Class<T>, rawObject: Record<string, any>): T {
  const instance = new instanceClass()
  Object.assign(instance, rawObject)
  return instance
}
```

**Comment by NickSeagull** [comment] 2021-08-02 07:50
Looks like a duplicate of #896 , gotta work on this

**Closed** 2021-08-30 14:22 UTC
Labels: bug
