### ISSUE TITLE
Implement boost status cli command

### ISSUE THREAD

**Issue by davidverdu** [boostercloud/booster#557] opened 2021-01-15 17:15 UTC
## Description

This command should display the status of your deployments, checking all defined environments, without deploying or nuking the application. The user will enter `boost status` inside the project folder to run this command.

## Possible Solution

Create a new command in the cli and define the command help for `boost --help`

**Comment by NickSeagull** [comment] 2021-01-20 10:47
It should also accept the `--environment` flag, so you can check a specific environment without checking them all.

**Comment by javiertoledo** [comment] 2021-02-04 18:30
Notice that we're already using the AWS SDKs in the integration tests package to get the appStack and get information about the deployed app. You can check the code here: https://github.com/boostercloud/booster/blob/main/packages/framework-integration-tests/integration/providers/aws/utils.ts#L75-L87

**Comment by jesusAlvSoto** [comment] 2022-04-19 12:28
Closing this issue as it is a duplicate of https://github.com/boostercloud/booster/issues/982

**Closed by jesusAlvSoto** 2022-04-19 12:28 UTC
Labels: enhancement, size: L
